/**
 * Centralised product and brand values.
 *
 * Everything user-visible that names the product or the brand comes from here,
 * so a rename is a single-file change.
 */

const PRODUCTION_URL = "https://pizzadough.southjerseysourdough.com";
const DEVELOPMENT_URL = "http://localhost:3000";

/**
 * Resolved site URL.
 *
 * Set NEXT_PUBLIC_SITE_URL in each deployed environment. The localhost default
 * exists so development works with no env file; it is the only fallback in the
 * codebase, which is why nothing else should hardcode a URL.
 */
function resolveSiteUrl(): string {
  const configured = process.env.NEXT_PUBLIC_SITE_URL;
  if (configured && configured.length > 0) return configured;
  return process.env.NODE_ENV === "production"
    ? PRODUCTION_URL
    : DEVELOPMENT_URL;
}

export const siteConfig = {
  /** Working product name. Do not change without an explicit request. */
  name: "Pizza Dough Calculator",
  brand: "South Jersey Sourdough",
  description:
    "Scale pizza dough by baking area, not guesswork. Baker's percentages, sourdough and pan support for steel, stone and sheet pan bakes.",

  url: resolveSiteUrl(),
  productionUrl: PRODUCTION_URL,
  developmentUrl: DEVELOPMENT_URL,

  /** Generated by src/app/opengraph-image.tsx. */
  ogImagePath: "/opengraph-image",

  seo: {
    title: "Pizza Dough Calculator",
    titleTemplate: "%s · Pizza Dough Calculator",
    description:
      "A precise pizza dough calculator for Baking Steel, stone and sheet pan bakes. Works in baker's percentages with sourdough, commercial yeast and hybrid formulas.",
  },
} as const;

export type SiteConfig = typeof siteConfig;
